### ISSUE TITLE
Add recipe to dynamically add tabs in a tab view

### ISSUE THREAD

**Issue by phochstr** [axonivy-market/html-dialog-utils#27]
See Zendesk [#4394](https://axonivy.zendesk.com/agent/tickets/4394).
Complete example supplied by @ivy-rew as an answer to the customer's query. 
Since that is a often-used construct, we will add it to the HTML dialog demos.

**Comment by ivy-rew** [comment]
> See Zendesk [#4394](https://axonivy.zendesk.com/agent/tickets/4394). Complete example supplied by @ivy-rew as an answer to the customer's query. Since that is a often-used construct, we will add it to the HTML dialog demos.

I think this is the wrong-repository for such a showcase; I'd rather add this to the 'html-dialog-demos' - > https://github.com/axonivy-market/demo-projects/tree/master/html-dialog
